version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    volumes:
      - ./app:/app
      - ./database:/database
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    container_name: househunter-app
    networks:
      - frontend  # Same network as Nginx Proxy Manager

networks:
  frontend:
    external: true  # Ensure this matches an existing external
